# Generated by Django 4.1.3 on 2022-11-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("rank", models.IntegerField(default=1)),
                ("point", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
