# Generated by Django 4.1.3 on 2022-11-30 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showtimes', '0001_initial'),
        ('m_users', '0001_initial'),
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterTicket',
            fields=[
                ('theater_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('m_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_users.muser')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showtimes.showtime')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theater')),
            ],
            options={
                'db_table': 'm_theater_tickets',
            },
        ),
    ]
