# Generated by Django 4.1.3 on 2022-11-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MUser",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.CharField(max_length=120, unique=True)),
                ("nickname", models.CharField(max_length=20, unique=True)),
                ("password", models.TextField(max_length=255)),
                ("age", models.IntegerField()),
            ],
            options={
                "db_table": "m_users",
            },
        ),
    ]
