# Generated by Django 4.1.3 on 2022-11-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m_users", "0002_alter_muser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
