# Generated by Django 4.1.4 on 2022-12-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BUser',
            fields=[
                ('b_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('nickname', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'b_users',
                'db_table': 'b_users',
            },
        ),
    ]
